version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    environment:
      - PHP_CONF_DISPLAY_ERRORS=On
      - PHP_CONF_DISPLAY_STARTUP_ERRORS=On
      - PHP_CONF_HTML_ERRORS=On
      - PHP_CONF_FPM_POOL_CLEAR_ENV=no
    env_file:
      - .env
      - .env.local
    volumes:
      - ./:/var/www

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
